### PR TITLE
Fix GRPC python gen issues

### PR DESCRIPTION
**Pull request by bjwatson**
* Use --grpc_python_out argument for Python, per https://github.com/grpc/grpc/issues/7857#issuecomment-243503869.
* Ensure that `gen-api-package` returns a non-zero status code when it fails (needed for remote pipeline to properly report a failure)

### CODE REVIEW

**Comment by jmuk** [comment]
Please fix the test failures.

Also -- I actually lgtm-ed the original design of introducing `--proto_compiler` flag, but as a second thought, packman should be intelligent enough to choose the proper proto compilers upon `-l` flag.

I mean, remove --proto_compiler flag, and then change the protoc command-line as `python -m grpc.tools.protoc --grpc_python_out=...` in packman (packman has the flag for language, so it knows it's for Python).

We already made special cases for Java and NodeJS in Packman, so I think this will be okay -- wdyt?

**Comment by bjwatson** [comment]
I started looking into doing it in Packman, because I agree that the logic belong there. However, it seems like a non-trivial refactor of the current code, especially since I'm new to NodeJS. I suggest we merge PRs like this for now, and create an issue to move this logic into Packman later (or whatever its replacement might be).

I'll fix the broken tests today.

**Comment by jmuk** [comment]
hm, that sounds legit.
Eitherway, I think packman needs some refactoring. It has too many special cases and someone needs to clean it up.

**Comment by jmuk** [comment]
Okay, LGTM. Let's discuss offline in the next week.

**Comment by bjwatson** [comment]
SGTM. I think @geigerj and @garrettjonesgoogle are also interested in that conversation.

**Pull request merged**
