### PR TITLE
Reset node/ruby package versions to 0.1.0.

### LINKED ISSUE #129: Ruby/Node: Reset the package version to 0.1.0
Since we've changed the delivery policy for Ruby and Node.JS -- now we are going to bring our generated code into google-cloud-(lang) repositories.

This would justify to reset the version numbers (in `config/api_defaults.yml`) to `0.1.0` probably.

### PR DESCRIPTION
**Pull request by jmuk**
Fixes #129

### CODE REVIEW

**Comment by geigerj** [comment]
Is there any potential for this to cause confusion with the existing packages on rubygems or npm?

**Comment by jmuk** [comment]
Problem would happen only when the published version moves back to lower one. Since the new APIs are not published yet, we could set any versions.

Having said that, this could cause potential inconsistency with other packages in google-cloud-(lang) repositories. For Node, it would be no problem, the version numbers vary. For Ruby, many of existing packages are `0.20.x` so this may look way too behind than others. I think that would be okay though.

Cc: @bjwatson

**Comment by bjwatson** [comment]
I left a similar comment on https://github.com/googleapis/packman/issues/129. I don't see much upside with doing this, and the potential for downside (at a minimum confusion).

I understand that this is technically okay since it's new packages, but I don't think it's necessary.

For example, we went from `gax-google-pubsub-v1 0.8.2` to `gapic-google-pubsub-v1 0.9.0`, and our counterparts went from `gcloud 0.18.1` to `google-cloud 0.19.0`.

**Comment by jmuk** [comment]
Okay, let's hold this and send PRs with the current versions. Revisit this when gcloud people raises concern about the versions.

**Pull request closed without merging**
