### PR TITLE
Update gRPC dependency for Python

### PR DESCRIPTION
**Pull request by bjwatson**

### CODE REVIEW

**Comment by bjwatson** [comment]
@jmuk @garrettjonesgoogle I noticed that your languages are on older versions of gRPC. Do they no longer use packman?

**Comment by garrettjonesgoogle** [comment]
@bjwatson No, Java does use packman. We are indeed on 0.15.0 currently.

**Comment by geigerj** [comment]
The tests are failing because one of the files edited is a test fixture (baseline), and the testdata comes from [here](https://github.com/bjwatson/packman/blob/0bdd216517b811665916c38eaf62ee5a47994ba7/test/packager.js#L162) instead of from the real configuration. You shouldn't need to change the tests to update the config.

**Comment by bjwatson** [comment]
@geigerj Does that mean the tests are rotting?

**Comment by garrettjonesgoogle** [comment]
I would prefer the term "maturing."

**Comment by geigerj** [comment]
I don't think the tests should depend on configuration at all -- I just think of the values in there as fake data.

**Comment by geigerj** [comment]
LGTM

**Comment by bjwatson** [comment]
@garrettjonesgoogle My term is so much more colorful. :)

Thanks @geigerj. I'll leave that value alone for now, but suggest we revisit it again later. It will confuse others (and possible me again) in the future.

**Pull request merged**
