### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by jmuk**

### CODE REVIEW

**Comment by ethanbao** [comment]
Brian did similar thing in https://github.com/googleapis/packman/pull/41/commits

**Comment by ethanbao** [comment]
LGTM

Please resolve the conflicts.

**Comment by jmuk** [comment]
rebased, as you see this PR updates a few other package dependencies to the latest version.
will merge soon.

**Comment by jmuk** [comment]
Updated python module version to 0.7.8 through the discussion with @bjwatson

**Pull request merged**
