### PR TITLE
Bump version for new release

### PR DESCRIPTION
**Pull request by geigerj**

### CODE REVIEW

**Comment by jmuk** [comment]
I think it's better to wait for https://github.com/googleapis/packman/pull/109 too (I've also forgotten about https://github.com/googleapis/packman/pull/95, but I want to have it as well, if possible).

**Comment by geigerj** [comment]
I needed to do this to fix artman remote stability issues -- I actually already published it to npm. Can we just bump to 0.8.5 for the outstanding issues?

**Comment by geigerj** [comment]
In any case, I think there is probably a bit more discussion to be had on #109 due to https://github.com/GoogleCloudPlatform/google-cloud-python/issues/1893#issuecomment-245410626

**Comment by jmuk** [comment]
LGTM if you've already pushed a new package to npm -- but the bug of #109 looks like you'll have to push yet another version quite soon after it's merged.

**Pull request merged**
