### PR TITLE
Fixed typo in python publishing readme.

### PR DESCRIPTION
**Pull request by Landrito**
Grammar fix as pointed out in [googleapis/api-client-staging/pull/21](https://github.com/googleapis/api-client-staging/pull/21)

### CODE REVIEW

**Comment by bjwatson** [comment]
Can you add the period, too?

**Comment by Landrito** [comment]
Done.

**Comment by Landrito** [comment]
@bjwatson PTAL. Looks like some of the links were broken as well.

**Comment by bjwatson** [comment]
LGTM

**Pull request merged**
